modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "radialhud"
version = "${version}"
displayName = "Radial Hud"
authors = "Cloudburst"
description = '''
Display your hotbar as a circle. Similar to GTA's HUD.
'''
logoFile = "icon.png"

[[dependencies.radialhud]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.radialhud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.radialhud]]
modId = "architectury"
mandatory = true
versionRange = "[5.7.28,)"
ordering = "AFTER"
side = "BOTH"